### ISSUE TITLE
Unable to save project

### ISSUE THREAD

**Issue by unknownprojectx-360** [odrick/free-tex-packer#36]
When there is a picture inside the project, it is unable to save project file (save project dialog box not open). It only can save when the project is empty.

OS: macOS Catalina (10.15.2)

**Comment by odrick** [comment]
Hi.

I don't have macOS and can't reproduse this bug...
In VirtualBox with macOS all ok.

**Comment by unknownprojectx-360** [comment]
You can try to update your virtualbox OS to macOS Catalina (10.15.2), Catalina has many security right blocking. Not only your software, many software has problem, does not work.

**Comment by N47x0** [comment]
Hi, I am on Windows 10.17763.973 and have been seeing this bug.
I think the issue may be related to the number of .png's I have loaded in the texture-sheet. I have been able to save "smaller textures". The issue arose under the following conditions:

- I have set the max "Width" and "Height" to "4096" (the max that my rendering infrastructure can handle).
- The Export works fine (with custom template), producing an "atlas file" according to my custom template (this works well!). It also produces a well formed png texture that is 1.88MB in size (not the max of 4096*4096).
- When using File->Save or "Ctrl-S" will not "finish saving" (*<project_name>.ftpp appears in the window chrome).
- When using File-Open Recent->"other project" a dialog with "Save project changes?" and "YES" "NO" "CANCEL" buttons appears: CANCEL and NO behave as expected (close dialog | close program without saving). But YES has no effect (dialog remains)
- the project saves any changes to the custom export template but will not load previously added image/textures.

Hope this info helps in diagnosing the issue. Let me know if there is any other info I can provide.

Otherwise, this is a pretty good tool! thank you for your work!

**Comment by shreddox** [comment]
Thanks N47x0, this helped me a lot!

I'm also on Windows 10 and I can't save a project either (nothing happens when clicking "Save project" or "Save project as...") when I drag & drop my sprites in.

As soon as I use the "Add images" or "Add Folder" button, I can suddenly save without a problem.

**Comment by alexvoz** [comment]
Windows 10, ver. 0.6.6. I can't save project with images. Maybe need clean installation - not update?
"**EDIT: I was able to save the project correctly by adding images with the "Add images" button in the desktop client - during most of the above attempts, I was using the "Drag & Drop" from a windows-explorer window to the desktop-client." - I have the same

**Comment by Cr0c81** [comment]
> **EDIT: I was able to save the project correctly by adding images with the "Add images" button in the desktop client - during most of the above attempts, I was using the "Drag & Drop" from a windows-explorer window to the desktop-client.
Same bug. Thanks for solution!

**Comment by odrick** [comment]
Fixed. Will be released at version 0.6.7
